version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  node-app-x3:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql-db
    links:
      - mysql-db
    networks:
      - app-tier
  mysql-db:
    image: mysql
    container_name: dbmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: "%"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
